version: "3"

services:
  bun:
    build:
      context: ./docker/bun
    command: sleep infinity
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ../:/workspace:cache

volumes:
  workspace: null
